export const ADD_WORK = "ADD_WORK";
export const SET_DONE = "SET_DONE";
export const SET_IN_PROGRESS = "SET_IN_PROGRESS";
export const DELETE_WORK = "DELETE_WORK";
export const FETCH_WEATHER_REQUEST = "FETCH_WEATHER_REQUEST";
export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";
export const FETCH_WEATHER_FAILURE = "FETCH_WEATHER_FAILURE";
